# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Github:
    url: https://github.com/Jevirs/Jevirs.github.io
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Jervis's

# URL of the Home page image
index_cover: /images/cover.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon: /images/icon.png

# Social Accounts
twitter_url: https://twitter.com/zhujiawei93
twitter_handle:
facebook_url: https://www.facebook.com/james.zhu.338863
github_url: https://github.com/Jevirs/Jevirs.github.io
gitlab_url:
linkedin_url:
mailto: z644658982@gmail.com