language: node_js
node_js:
  - "8"

# 缓存node_modules
cache:
 directories:
   - node_modules

# 源码所在分支
branches:
only:
- source

# 安装依赖
install:
- npm install

# 执行的命令
script:
- hexo clean
- hexo g

# 部署
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: source

notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=b16ce1814cd5e856dc6e8d4d7ba6d8b58963bad777867515210a29252874aadb