language: node_js
node_js: node

# 缓存node_modules
cache:
directories:
- node_modules

# 源码所在分支
branches:
only:
- master

# 安装依赖
install:
- npm install

# 执行的命令
script:
- hexo clean
- hexo generate

# 部署
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: public
  on:
    branch: master